name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: cd ./SqlBackupJanitor && dotnet build --configuration Release
    - name: Test Project
      run: cd ./SqlBackupJanitor && dotnet test
    - name: Publish
      run: cd ./SqlBackupJanitor && dotnet publish --runtime win-64
